services:
  logstash:
    image: logstash:8.11.1
    container_name: logstash-kafka
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - LS_JAVA_OPTS=-Xmx8g -Xms4g
    networks:
      - elasticsearch-poc

networks:
  elasticsearch-poc:
    external: true
