include:
  - ./elasticsearch-include.yaml
  - ./opensearch-include.yaml
  - ./kafka-include.yaml

services:
  debugging:
    build:
      dockerfile_inline: |
        FROM alpine:latest
        RUN apk update &&\
          apk add \
            bind-tools \
            net-tools

    container_name: debugging
    command:
      - ash
      - -c
      - >
        while true; do sleep 3600; done
    networks:
      - elasticsearch-poc
